/**
 * DOM registry for CharBrowser frontend modules.
 * Modules consume this object instead of repeating document queries in each file.
 */
export const dom = {
    openFolderBtn: document.getElementById('openFolderBtn'),
    showLicensesBtn: document.getElementById('showLicensesBtn'),
    dropZone: document.getElementById('dropZone'),
    metadataView: document.getElementById('metadataView'),
    fileList: document.getElementById('fileList'),
    folderPath: document.getElementById('folderPath'),
    fileNameFilter: document.getElementById('fileNameFilter'),
    fileTypeFilter: document.getElementById('fileTypeFilter'),
    mediaOnlyToggle: document.getElementById('mediaOnlyToggle'),
    metadataWordFilter: document.getElementById('metadataWordFilter'),
    hasEmbeddedJsonOnly: document.getElementById('hasEmbeddedJsonOnly'),
    hasExifOnly: document.getElementById('hasExifOnly'),
    sortByFilter: document.getElementById('sortByFilter'),
    sortDirectionFilter: document.getElementById('sortDirectionFilter'),
    folderFilterStatus: document.getElementById('folderFilterStatus'),
    preview: document.getElementById('preview'),
    videoPreview: document.getElementById('videoPreview'),
    audioPreview: document.getElementById('audioPreview'),
    previewStage: document.querySelector('.preview-stage'),
    noPreview: document.getElementById('noPreview'),
    characterTextPanel: document.getElementById('characterTextPanel'),
    characterDescription: document.getElementById('characterDescription'),
    characterFirstMes: document.getElementById('characterFirstMes'),
    metadataContent: document.getElementById('metadataContent'),
    sidebarSplitter: document.getElementById('sidebarSplitter'),
    metadataSplitter: document.getElementById('metadataSplitter'),
    embeddedJsonSection: document.getElementById('embeddedJsonSection'),
    embeddedJsonFormatFilter: document.getElementById('embeddedJsonFormatFilter'),
    embeddedJsonTextFilter: document.getElementById('embeddedJsonTextFilter'),
    embeddedJsonSelect: document.getElementById('embeddedJsonSelect'),
    embeddedJsonPayloadLabel: document.getElementById('embeddedJsonPayloadLabel'),
    embeddedJsonPayloadPreview: document.getElementById('embeddedJsonPayloadPreview'),
    embeddedJsonTree: document.getElementById('embeddedJsonTree'),
    saveEmbeddedJsonBtn: document.getElementById('saveEmbeddedJsonBtn'),
    copyMetadataBtn: document.getElementById('copyMetadataBtn'),
    embeddedJsonStatus: document.getElementById('embeddedJsonStatus'),
    jsonDiffModal: document.getElementById('jsonDiffModal'),
    jsonDiffSummary: document.getElementById('jsonDiffSummary'),
    jsonDiffOriginal: document.getElementById('jsonDiffOriginal'),
    jsonDiffEdited: document.getElementById('jsonDiffEdited'),
    confirmJsonSaveBtn: document.getElementById('confirmJsonSaveBtn'),
    cancelJsonSaveBtn: document.getElementById('cancelJsonSaveBtn'),
    licensesModal: document.getElementById('licensesModal'),
    licensesMeta: document.getElementById('licensesMeta'),
    licensesSearchInput: document.getElementById('licensesSearchInput'),
    licensesEcosystemFilter: document.getElementById('licensesEcosystemFilter'),
    licensesTableBody: document.getElementById('licensesTableBody'),
    closeLicensesBtn: document.getElementById('closeLicensesBtn'),
    openNoticesFileLink: document.getElementById('openNoticesFileLink'),
    docViewerModal: document.getElementById('docViewerModal'),
    docViewerTitle: document.getElementById('docViewerTitle'),
    docViewerContent: document.getElementById('docViewerContent'),
    closeDocViewerBtn: document.getElementById('closeDocViewerBtn'),
    textEntriesSection: document.getElementById('textEntriesSection'),
    textEntriesSelect: document.getElementById('textEntriesSelect'),
    textEntriesContent: document.getElementById('textEntriesContent'),
    textEntriesStatus: document.getElementById('textEntriesStatus'),
};
